version: "3.3"
services:

  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    build:
      context: debezium-connect
    ports:
     - 8083:8083
    networks:
      - default
      - openlmis-ref-distro_default
    environment:
     - BOOTSTRAP_SERVERS=kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - HOST_NAME=0.0.0.0

  kafka-rest:
    image: confluentinc/cp-kafka-rest
    ports:
     - 8082:8082
    environment:
     - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:32181
     - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:29092
     - KAFKA_REST_HOST_NAME=kafka-rest
     - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
     - KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS=30000
     - KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
     - KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN=*

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    hostname: topics_ui
    ports:
      - 8000:8000
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true
      - MAX_BYTES=500000

networks:
 openlmis-ref-distro_default:
   external: true
